import type { Metadata } from "next";
import { outfit, dmSerifDisplay, dmMono } from "@/config/fonts";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Zohaib Ashraf | Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/favicons/favicon-16x16.png", sizes: "16x16" },
      { url: "/favicons/favicon-32x32.png", sizes: "32x32" },
      { url: "/favicons/favicon-64x64.png", sizes: "64x64" },
    ],
    apple: "/favicons/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${outfit.variable} ${dmSerifDisplay.variable} ${dmMono.variable} h-full w-full`}
    >
      <body className="h-full w-full bg-[#060A07]">{children}</body>
    </html>
  );
}
